services:
  auth_service:
    build: ./auth-service
    command: fastapi dev src/main.py --host 0.0.0.0 --port 8000 # TODO: write command
    volumes:
      - ./auth-service/:/app/
    ports:
      - 8001:8000
    environment:
      - DATABASE_URI=postgresql://auth_username:auth_password@auth_db/auth_db
    env_file: ./auth-service/.env

  auth_db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data_auth:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=auth_username
      - POSTGRES_PASSWORD=auth_password
      - POSTGRES_DB=auth_db

  todo_service:
    build: ./todo-service
    command: fastapi dev src/main.py --host 0.0.0.0 --port 8000 # TODO: write command
    volumes:
      - ./todo-service/:/app/
    ports:
      - 8002:8000
    environment:
      - DATABASE_URI=postgresql://todo_username:todo_password@todo_db/todo_username
      - AUTH_SERVICE_HOST_URL=http://auth_service:8000/api/v1
    env_file: ./todo-service/.env

  todo_db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data_todo:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=todo_username
      - POSTGRES_PASSWORD=todo_password
      - POSTGRES_DB=todo_db

volumes:
  postgres_data_auth:
  postgres_data_todo:
